### ISSUE TITLE
Remove scenario from db using 

### ISSUE THREAD

**Issue by byersiiasa** [iiasa/ixmp#406] opened 2021-03-19 18:55 UTC
Remove scenario from db using backend using `mp._backend.jobj.removeRunid(run_id)` method (possibly deprecated?

```
import ixmp
mp = ixmp.Platform(dbprops=config)
model = "GEMINI-E3\+CHE\+3.0"  ## horrible name hence removal
scenario = '10TPC_etsUni'
s = ixmp.Scenario(mp, model, scenario, version=1)
run_id = s.run_id()
mp._backend.jobj.removeRunid(run_id)

Traceback (most recent call last):

  File "Platform.java", line 201, in at.ac.iiasa.ixmp.Platform.removeRunid

  File "DbDAO.java", line 628, in at.ac.iiasa.ixmp.database.DbDAO.setStatus

  File "DbDAO.java", line 634, in at.ac.iiasa.ixmp.database.DbDAO.setStatus

  File "DbDAO.java", line 1088, in at.ac.iiasa.ixmp.database.DbDAO.loggedIxException

Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-94-8ce65f2499bd>", line 1, in <module>
    mp._backend.jobj.removeRunid(run_id)

at.ac.iiasa.ixmp.exceptions.IxException: at.ac.iiasa.ixmp.exceptions.IxException: Cannot set scenario status to NONE
```

Expected scenario to be removed. Tested this on both ar6 and ar6_sanbox databases.

I tried looking in the docs and the source code but I don't see it under the Platform class. I don't think the method was documented originally also.

Thanks in advance

#### Versions

ixmp:        3.2.1.dev41+g6e52639
message_ix:  None
message_data: None

click:       7.1.2
dask:        2.30.0
graphviz:    0.14.2
jpype:       1.2.1
… JVM path:  C:\Program Files\Java\jre1.8.0_271\bin\server\jvm.dll
openpyxl:    3.0.5
pandas:      1.1.5
pint:        0.16.1
xarray:      0.16.2
yaml:        5.3.1

iam_units:   installed
jupyter:     installed
matplotlib:  3.3.3
plotnine:    None
pyam:        0.8.0+40.ge027675
     e027675 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'danielhuppmann-io/excel-multiple-sheet'

GAMS:        'gams' executable not in PATH

python:      3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS:          Windows
OS-release:  10
machine:     AMD64
processor:   Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder:   little
LC_ALL:      None
LANG:        en
LOCALE:      English_United Kingdom.utf8

'gams' is not recognized as an internal or external command,
operable program or batch file.

</details>

**Comment by khaeru** [comment] 2021-03-20 12:24
This is a duplicate of #382. The status quo as described at https://github.com/iiasa/ixmp/issues/382#issuecomment-729787664 remains.

**Closed by khaeru** 2021-03-20 12:24 UTC
Labels: backend.jdbc, bug
