### ISSUE TITLE
Add Backend method like TimeSeries.unlock()

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/ixmp#234] opened 2019-12-11 12:10 UTC
When a script fails and a scenario is checked out, then there is no possibility to unlock the scenario.  Previously, there used to be a possibility to do this using the command mp.._jobj.unlockRunid(). This is of course not ideal as it was more of a backdoor solution, but this feature would be nice for expert users, which is no longer available since switching to the new backend.

**Comment by khaeru** [comment] 2019-12-11 13:26
[Backend API docs](https://message.iiasa.ac.at/projects/ixmp/en/master/api-backend.html#ixmp.backend.base.Backend), for reference.

Some thoughts:
- The `.check_out()`/`.commit()` methods are in TimeSeries, rather than Scenario.
- I've always felt these were a weird hybrid of SQL and git semantics.
  - In SQL, there is nothing like `CHECK_OUT`, only `COMMIT`, `ROLLBACK`, and some others.
    - ixmp lacks anything like `ROLLBACK`.
  - `git checkout` modifies or *reverts* the working tree.
    - In most workflows, it is not needed to call it before modifying files.
    - Often, when used, its meaning is actually closer to SQL `ROLLBACK`: `git checkout -- file.txt` rolls back file.txt to its content as of the last commit.
  - Neither includes a notion of locking.
- `.check_out()` and `.commit()` actually do TWO things:
  - Manage transactions.
  - Locking.
- The 'locked' status of a TimeSeries seems to mean 'locked for other users'.
  - ixmp.Platform and base.Backend don't explicitly discuss the (possibly) multi-user nature of Backends.
  - In SQL, if a transaction fails or is rolled back, it is simply not committed, and nothing prevents another set of modifications from starting immediately.

**Comment by khaeru** [comment] 2020-02-11 09:46
Duplicate of #30, which is about 1.5 years older.

**Closed by khaeru** 2020-02-11 09:46 UTC
Labels: enhancement
